# Generated by Django 3.2.9 on 2021-11-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.ManyToManyField(to='api.Room'),
        ),
    ]
