# Generated by Django 3.2.9 on 2021-11-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211123_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_str',
            field=models.TextField(default='Default'),
        ),
    ]
